# Generated by Django 5.2.7 on 2025-10-21 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
